version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - portfolio_data:/var/lib/postgresql/data

volumes:
  portfolio_data:
